version: '3.7'

services:
  api:
    container_name: api
    build: ./vue_backend
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn vuebackend.wsgi:application -w 2 -k gthread -b :8000
    volumes:
      - ./vue_backend/:/usr/src/api/
      - static_volume:/usr/src/api/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - nginx
    networks:
      - django-nginx
  redis:
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    image: redis
    networks:
      - django-nginx
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - django-nginx
  nginx:
    container_name: nginx
    build: ./fontend
    restart: always
    volumes:
      - static_volume:/usr/src/api/static
      - ./fontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - 8088:80
    networks:
      - django-nginx

networks:
  django-nginx:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
