# Generated by Django 3.0 on 2020-02-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.IntegerField(default=1)),
                ('is_manager', models.IntegerField(default=1)),
                ('is_sale_manage', models.IntegerField(default=1)),
                ('is_sales', models.IntegerField(default=1)),
                ('is_purchase_manage', models.IntegerField(default=1)),
                ('is_purchase', models.IntegerField(default=1)),
                ('is_ship_manage', models.IntegerField(default=1)),
                ('is_ship', models.IntegerField(default=1)),
                ('is_finance_manage', models.IntegerField(default=1)),
                ('is_finance', models.IntegerField(default=1)),
                ('u_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
    ]
