# Generated by Django 3.0 on 2020-02-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='permissions',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
