# Generated by Django 3.0 on 2020-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200217_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_use',
            field=models.IntegerField(default=0),
        ),
    ]
