# Generated by Django 3.0 on 2020-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercatalog',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='金额'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='lite_name',
            field=models.CharField(help_text='如无公司则填联系人或CEO名称', max_length=32, primary_key=True, serialize=False, verbose_name='公司简称'),
        ),
    ]
