# Generated by Django 3.0 on 2020-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200112_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
