# Generated by Django 3.0 on 2020-02-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200202_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='pro_color',
            field=models.CharField(default='color', max_length=64, verbose_name='产品颜色'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='pro_pack',
            field=models.CharField(default='无', max_length=64, verbose_name='产品包装'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='pro_size',
            field=models.CharField(default=0, max_length=64, verbose_name='产品尺寸'),
        ),
    ]
