# Generated by Django 3.0 on 2020-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200126_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercatalog',
            name='order_pic',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
