# Generated by Django 3.0 on 2020-02-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200213_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiporder',
            name='destination',
            field=models.CharField(default='American', max_length=32),
        ),
    ]
