# Generated by Django 3.0 on 2020-02-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shiporder_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='website',
            field=models.URLField(default='https://example.com', verbose_name='网址'),
        ),
    ]
