# Generated by Django 3.0 on 2020-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200218_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='is_reconciliation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customers',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordercatalog',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordercatalog',
            name='is_done',
            field=models.IntegerField(choices=[(1, '未完成'), (2, '已完成'), (3, '已超期'), (4, '紧急')], default=0, verbose_name='完成状态'),
        ),
        migrations.AlterField(
            model_name='ordercatalog',
            name='ship_addr',
            field=models.CharField(default='暂无', max_length=200, verbose_name='出货地点'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productstype',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipdetail',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shiporder',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='is_account',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='is_purchase',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='is_ship',
            field=models.IntegerField(default=0),
        ),
    ]
