# Generated by Django 3.0 on 2020-02-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200220_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercatalog',
            name='is_done',
            field=models.IntegerField(choices=[(1, '未完成'), (2, '已完成'), (3, '已超期'), (4, '紧急')], default=0, verbose_name='状态'),
        ),
    ]
