# Generated by Django 3.0 on 2020-02-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200221_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercatalog',
            name='is_done',
            field=models.IntegerField(choices=[(0, '正常'), (1, '紧急')], default=0, verbose_name='状态'),
        ),
    ]
