# Generated by Django 3.0 on 2020-02-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200126_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='static/image/%Y-%m/'),
        ),
    ]
