# Generated by Django 3.0 on 2020-02-24 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200221_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='md5',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='up_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
